

FUNCTION_BLOCK FB_SimBasicExitConveyor EXTENDS FB_BaseComponent IMPLEMENTS IExitConveyor, IExecuteAutomatically
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR



METHOD BeginDischarge

_logger.AddLogItem(CONCAT(_prefix, 'Begin Discharge'));

FUNCTION_BLOCK FB_SimBasicExitConveyor EXTENDS FB_BaseComponent IMPLEMENTS IExitConveyor, IExecuteAutomatically
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR



METHOD BeginDischarge

_logger.AddLogItem(CONCAT(_prefix, 'Begin Discharge'));