

{attribute 'FBVisuCreator'}
FUNCTION_BLOCK FB_Simulation
VAR_INPUT
	failedToGrabBagLeftFinger : BOOL;
	failedToGrabBagRightFinger : BOOL;
	failedToGrabBagBothFingers : BOOL;
	pressureBarFailedToMoveIn : BOOL;
	pressureBarFailedToMoveOut : BOOL;
	pressureBarObstucted : BOOL;
	pressureBarfailedToHome : BOOL;
	passthroughMotorFault : BOOL;
	failedToMovePassthrough : BOOL;
	msfHorizontalFailedToHome : BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR

