(*#-#-#-#-#-#-#-#-#-#---Declaration---#-#-#-#-#-#-#-#-#-#-#-#-#*)
{attribute 'qualified_only'}
VAR_GLOBAL PERSISTENT RETAIN


	// Generated instance path of persistent variable
	Main_PRG.machineComponents.standardBagOpenFingersWithSensors.grabCounter.count: UDINT;
	// Generated instance path of persistent variable
	Main_PRG.machineComponents.standardBagOpenFingersWithSensors.releaseCounter.count: UDINT;
	// Generated instance path of persistent variable
	Main_PRG.machineComponents.standardBagOpenFingersWithSensors.missedCounter.count: UDINT;
	// Generated instance path of persistent variable
	HMI.data.pressureBarCycles.count: UDINT;
END_VAR