(*#-#-#-#-#-#-#-#-#-#---Declaration---#-#-#-#-#-#-#-#-#-#-#-#-#*)
{attribute 'qualified_only'}
{attribute 'strict'}
TYPE TL50Colors :
(
	Green := 0,
    Red := 1,
    Orange := 2,
    Amber := 3,
    Yellow := 4,
    LimeGreen := 5,
    SpringGreen := 6,
    Cyan := 7,
    SkyBlue := 8,
    Blue := 9,
    Violet := 10,
    Magenta := 11,
    Rose := 12,
    White := 13,
    Custom1 := 14,
    Custom2 := 15
) BYTE ;
END_TYPE
