//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Expressions : Neo.ApplicationFramework.Tools.Expressions.ExpressionManager, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Expressions()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
		}
		
		private void InitializeBeginInits()
		{
		}
		
		private void InitializeEndInits()
		{
		}
		
		public Neo.ApplicationFramework.Interfaces.VariantValue UserBlank(Neo.ApplicationFramework.Interfaces.VariantValue value)
		{
			return value == "";
		}
		
		public Neo.ApplicationFramework.Interfaces.VariantValue greaterThan1(Neo.ApplicationFramework.Interfaces.VariantValue value)
		{
			return value > 1;
		}
		
		public Neo.ApplicationFramework.Interfaces.VariantValue MoreObjectsThandisplayed(Neo.ApplicationFramework.Interfaces.VariantValue value)
		{
			return ((value) *6)<Globals.Tags.Application_GlobalObjects_CollectionOfComponents_TotalObjects.Value;
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Expressions));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
