(*#-#-#-#-#-#-#-#-#-#---Declaration---#-#-#-#-#-#-#-#-#-#-#-#-#*)
TYPE AuxIOConfiguration :
STRUCT
	factorySelection : AuxiliaryIOSelection;
	cfgInput1Selection : AuxInputSelection;
	cfgInput2Selection : AuxInputSelection;
	cfgInput3Selection : AuxInputSelection;
	cfgInput4Selection : AuxInputSelection;
	cfgOutput1Selection : AuxOutputSelection;
	cfgOutput2Selection : AuxOutputSelection;
	cfgOutput3Selection : AuxOutputSelection;
	cfgOutput4Selection : AuxOutputSelection;
END_STRUCT
END_TYPE
