//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Advanced_P3 : BaseTemplate, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle3;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle2;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle5;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric2;
        
        private bool m_Initialized_Advanced_P3;
        
        public Advanced_P3() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric2);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle3 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle2 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric1 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_Rectangle4 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle5 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric2 = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).BeginInit();
            this.SuspendLayout();
            // 
            // Advanced_P3
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 16;
            this.m_Text.Height = 21;
            this.m_Text.Left = 233;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text.ScreenOwnerName = "Advanced_P3";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 0;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 54;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 14;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 260;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3.5D, 0D, 3.5D, 1D);
            this.m_Text1.ScreenOwnerName = "Advanced_P3";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 25;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 23;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontSizePixels = 9;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 46;
            this.m_Button.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 420;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Advanced_P3";
            this.m_Button.SymbolHeight = 30;
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.SymbolName = "ag_arrow right green";
            this.m_Button.SymbolWidth = 37;
            this.m_Button.TextHeight = 11;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 50;
            this.m_Button.Top = 0;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = 1749738280;
            this.m_Button.Width = 60;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 9;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 46;
            this.m_Button1.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 360;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "Advanced_P3";
            this.m_Button1.SymbolHeight = 30;
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.SymbolName = "ag_arrow left green";
            this.m_Button1.SymbolWidth = 37;
            this.m_Button1.TextHeight = 11;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 50;
            this.m_Button1.Top = 0;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 629769305;
            this.m_Button1.Width = 60;
            // 
            // m_Rectangle3
            // 
            this.m_Rectangle3.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle3.BlinkDynamicsValue = false;
            this.m_Rectangle3.DelayMouseInputPeriod = 0;
            this.m_Rectangle3.EnabledDynamicsValue = true;
            this.m_Rectangle3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle3.Height = 24;
            this.m_Rectangle3.Left = 149;
            this.m_Rectangle3.Name = "m_Rectangle3";
            this.m_Rectangle3.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle3.Top = 105;
            this.m_Rectangle3.VisibleDynamicsValue = true;
            this.m_Rectangle3.Width = 204;
            // 
            // m_Rectangle2
            // 
            this.m_Rectangle2.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle2.BlinkDynamicsValue = false;
            this.m_Rectangle2.DelayMouseInputPeriod = 0;
            this.m_Rectangle2.EnabledDynamicsValue = true;
            this.m_Rectangle2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Height = 24;
            this.m_Rectangle2.Left = 352;
            this.m_Rectangle2.Name = "m_Rectangle2";
            this.m_Rectangle2.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle2.Top = 105;
            this.m_Rectangle2.VisibleDynamicsValue = true;
            this.m_Rectangle2.Width = 57;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Height = 24;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 0;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 97;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 24;
            this.m_Rectangle1.Left = 96;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 0;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 72;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_Rectangle);
            this.m_Group.Components.Add(this.m_Rectangle1);
            this.m_Group.DelayMouseInputPeriod = 0;
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 24;
            this.m_Group.Left = 191;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "Advanced_P3";
            this.m_Group.Top = 72;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 168;
            // 
            // m_Text2
            // 
            this.m_Text2.AutoSize = false;
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 10;
            this.m_Text2.Height = 24;
            this.m_Text2.Left = 191;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2.5D, 0D, 2.5D, 1D);
            this.m_Text2.ScreenOwnerName = "Advanced_P3";
            this.m_Text2.TextVerticalAlignment = "Center";
            this.m_Text2.Top = 72;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 97;
            // 
            // m_AnalogNumeric1
            // 
            this.m_AnalogNumeric1.BlinkDynamicsValue = false;
            this.m_AnalogNumeric1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric1.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric1.EnabledDynamicsValue = true;
            this.m_AnalogNumeric1.FontSizePixels = 14;
            this.m_AnalogNumeric1.Height = 24;
            this.m_AnalogNumeric1.Left = 287;
            this.m_AnalogNumeric1.LimitNumberOfCharacters = true;
            this.m_AnalogNumeric1.MaxNumberOfCharacters = 7;
            this.m_AnalogNumeric1.MaxValue = 30000000D;
            this.m_AnalogNumeric1.Name = "m_AnalogNumeric1";
            this.m_AnalogNumeric1.NumberOfDecimals = 0;
            this.m_AnalogNumeric1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric1.ScreenOwnerName = "Advanced_P3";
            this.m_AnalogNumeric1.Top = 72;
            this.m_AnalogNumeric1.ValidateValueOnInput = true;
            this.m_AnalogNumeric1.VisibleDynamicsValue = true;
            this.m_AnalogNumeric1.Width = 72;
            // 
            // m_Text3
            // 
            this.m_Text3.AutoSize = false;
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.Bold = true;
            this.m_Text3.DelayMouseInputPeriod = 0;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 10;
            this.m_Text3.Height = 24;
            this.m_Text3.Left = 149;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2.5D, 0D, 2.5D, 1D);
            this.m_Text3.ScreenOwnerName = "Advanced_P3";
            this.m_Text3.TextVerticalAlignment = "Center";
            this.m_Text3.Top = 105;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 204;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 14;
            this.m_AnalogNumeric.Height = 24;
            this.m_AnalogNumeric.Left = 352;
            this.m_AnalogNumeric.LimitNumberOfCharacters = true;
            this.m_AnalogNumeric.MaxNumberOfCharacters = 5;
            this.m_AnalogNumeric.MaxValue = 30D;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.NumberOfDecimals = 2;
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ScreenOwnerName = "Advanced_P3";
            this.m_AnalogNumeric.Top = 105;
            this.m_AnalogNumeric.ValidateValueOnInput = true;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 57;
            // 
            // m_Rectangle4
            // 
            this.m_Rectangle4.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle4.BlinkDynamicsValue = false;
            this.m_Rectangle4.DelayMouseInputPeriod = 0;
            this.m_Rectangle4.EnabledDynamicsValue = true;
            this.m_Rectangle4.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle4.Height = 24;
            this.m_Rectangle4.Left = 149;
            this.m_Rectangle4.Name = "m_Rectangle4";
            this.m_Rectangle4.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle4.Top = 137;
            this.m_Rectangle4.VisibleDynamicsValue = true;
            this.m_Rectangle4.Width = 204;
            // 
            // m_Rectangle5
            // 
            this.m_Rectangle5.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle5.BlinkDynamicsValue = false;
            this.m_Rectangle5.DelayMouseInputPeriod = 0;
            this.m_Rectangle5.EnabledDynamicsValue = true;
            this.m_Rectangle5.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle5.Height = 24;
            this.m_Rectangle5.Left = 352;
            this.m_Rectangle5.Name = "m_Rectangle5";
            this.m_Rectangle5.ScreenOwnerName = "Advanced_P3";
            this.m_Rectangle5.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle5.Top = 137;
            this.m_Rectangle5.VisibleDynamicsValue = true;
            this.m_Rectangle5.Width = 57;
            // 
            // m_Text4
            // 
            this.m_Text4.AutoSize = false;
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.Bold = true;
            this.m_Text4.DelayMouseInputPeriod = 0;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 10;
            this.m_Text4.Height = 24;
            this.m_Text4.Left = 149;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2.5D, 0D, 2.5D, 1D);
            this.m_Text4.ScreenOwnerName = "Advanced_P3";
            this.m_Text4.TextVerticalAlignment = "Center";
            this.m_Text4.Top = 137;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 204;
            // 
            // m_AnalogNumeric2
            // 
            this.m_AnalogNumeric2.BlinkDynamicsValue = false;
            this.m_AnalogNumeric2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric2.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric2.DisplayFormat = Neo.ApplicationFramework.Interfaces.AnalogNumericDisplayFormat.Decimal;
            this.m_AnalogNumeric2.EnabledDynamicsValue = true;
            this.m_AnalogNumeric2.FontSizePixels = 14;
            this.m_AnalogNumeric2.Height = 24;
            this.m_AnalogNumeric2.Left = 352;
            this.m_AnalogNumeric2.LimitNumberOfCharacters = true;
            this.m_AnalogNumeric2.MaxNumberOfCharacters = 5;
            this.m_AnalogNumeric2.MinValue = -1D;
            this.m_AnalogNumeric2.Name = "m_AnalogNumeric2";
            this.m_AnalogNumeric2.NumberOfDecimals = 2;
            this.m_AnalogNumeric2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric2.ScreenOwnerName = "Advanced_P3";
            this.m_AnalogNumeric2.Top = 137;
            this.m_AnalogNumeric2.ValidateValueOnInput = true;
            this.m_AnalogNumeric2.VisibleDynamicsValue = true;
            this.m_AnalogNumeric2.Width = 57;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(480, 272);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Advanced_P3";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Advanced_P3 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Advanced_P3) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Rectangle3);
            this.DrawingPrimitives.Add(this.m_Rectangle2);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Group);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric1);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_Rectangle4);
            this.DrawingPrimitives.Add(this.m_Rectangle5);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric2);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric2)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "Advanced_P4", "");
            Neo.ApplicationFramework.Generated.Globals.Advanced_P4.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "Advanced_P2", "");
            Neo.ApplicationFramework.Generated.Globals.Advanced_P2.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Advanced_P3));
            this.m_Text.Text = resources.GetText("Advanced_P3.Text.Text", "Advanced");
            this.m_Text1.Text = resources.GetText("Advanced_P3.Text1.Text", "3/4");
            this.m_Text2.Text = resources.GetText("Advanced_P3.Text2.Text", "    Bags Made");
            this.m_Text3.Text = resources.GetText("Advanced_P3.Text3.Text", "    Standby Time (Min.)");
            this.m_Text4.Text = resources.GetText("Advanced_P3.Text4.Text", "    Jaw Close (in.)");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled());
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Advanced_P3) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_bagsMade"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric1.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_standbyTimeSetting"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_jawClosePositionSetting"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric2.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
        }
    }
}
