(*#-#-#-#-#-#-#-#-#-#---Declaration---#-#-#-#-#-#-#-#-#-#-#-#-#*)
METHOD Executing
(*#-#-#-#-#-#-#-#-#-#---Implementation---#-#-#-#-#-#-#-#-#-#-#-#-#*)
//	Method: EM01_Bagger_MaintMode.Executing()
//	Description: Executing is the state in which the machine is ready to accept "service commands".  
//				 
//	Created by: Ben Hess
//	Created Date: Tuesday, March 27, 2019
_startingDone := FALSE;
