(*#-#-#-#-#-#-#-#-#-#---Declaration---#-#-#-#-#-#-#-#-#-#-#-#-#*)
{attribute 'qualified_only'}
VAR_GLOBAL
	iPAPrintEnginePower : BOOL;
	iPAPrintEngineError : BOOL;
	iPARibbonLow : BOOL;
	iPALabelOut : BOOL;
	iPAOnlineDataReady : BOOL;
	iPARibbonOut : BOOL;
	iPAVacuumSensor : BOOL;
	iPAFaulted : BOOL;
	iPACycleComplete : BOOL;
	iPAApplicatorHome : BOOL;
	iPALowLabels : BOOL;
	iPALOTAR : BOOL;
	iPABypassOn : BOOL;
	iPAHeartbeat : BOOL;
	oPATrigger1 : BOOL;
	oPAReset : BOOL;
	oPABypassEnable : BOOL;
END_VAR