#pragma warning disable 0108
#pragma warning disable 0114
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Service_P3 : BaseTemplate, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private bool m_Initialized_Service_P3;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf3;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf4;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf5;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf6;
        
        public Service_P3() {
            this.InitializeComponent();
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button2.MouseDown += new System.EventHandler(this.m_Button2_Action_PreviewMouseDown);
            this.m_Button2.MouseUp += new System.EventHandler(this.m_Button2_Action_PreviewMouseUp);
            this.m_Button2.MouseLeave += new System.EventHandler(this.m_Button2_Action_MouseLeave);
            this.m_Button5.MouseDown += new System.EventHandler(this.m_Button5_Action_PreviewMouseDown);
            this.m_Button5.MouseUp += new System.EventHandler(this.m_Button5_Action_PreviewMouseUp);
            this.m_Button5.MouseLeave += new System.EventHandler(this.m_Button5_Action_MouseLeave);
            this.m_Button6.MouseDown += new System.EventHandler(this.m_Button6_Action_PreviewMouseDown);
            this.m_Button6.MouseUp += new System.EventHandler(this.m_Button6_Action_PreviewMouseUp);
            this.m_Button6.MouseLeave += new System.EventHandler(this.m_Button6_Action_MouseLeave);
            this.m_Button7.MouseDown += new System.EventHandler(this.m_Button7_Action_PreviewMouseDown);
            this.m_Button7.MouseUp += new System.EventHandler(this.m_Button7_Action_PreviewMouseUp);
            this.m_Button7.MouseLeave += new System.EventHandler(this.m_Button7_Action_MouseLeave);
            this.m_Button.MouseDown += new System.EventHandler(this.m_Button_Action_PreviewMouseDown);
            this.m_Button.MouseUp += new System.EventHandler(this.m_Button_Action_PreviewMouseUp);
            this.m_Button.MouseLeave += new System.EventHandler(this.m_Button_Action_MouseLeave);
            this.m_Button4.MouseDown += new System.EventHandler(this.m_Button4_Action_PreviewMouseDown);
            this.m_Button4.MouseUp += new System.EventHandler(this.m_Button4_Action_PreviewMouseUp);
            this.m_Button4.MouseLeave += new System.EventHandler(this.m_Button4_Action_MouseLeave);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf6 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf5 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf4 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf3 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval5 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval6 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf3 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf5 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf6 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval7 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval8 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf4 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf7 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf8 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval9 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval10 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval11 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval12 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            this.SuspendLayout();
            // 
            // Service_P3
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 9;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 46;
            this.m_Button1.ImageMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(5D, 5D, 5D, 5D);
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 360;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "Service_P3";
            this.m_Button1.SymbolHeight = 30;
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button1.SymbolName = "ag_arrow left green";
            this.m_Button1.SymbolWidth = 37;
            this.m_Button1.TextHeight = 11;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 50;
            this.m_Button1.Top = 0;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 629769305;
            this.m_Button1.Width = 60;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.Bold = true;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 16;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Text.Height = 21;
=======
            this.m_Text.Height = 28;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Text.Left = 220;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(4D, 0D, 4D, 1D);
            this.m_Text.ScreenOwnerName = "Service_P3";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.TextVerticalAlignment = "Center";
            this.m_Text.Top = 0;
            this.m_Text.VisibleDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Text.Width = 69;
=======
            this.m_Text.Width = 111;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.Bold = true;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 14;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Text1.Height = 21;
=======
            this.m_Text1.Height = 28;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Text1.Left = 260;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(3.5D, 0D, 3.5D, 1D);
            this.m_Text1.ScreenOwnerName = "Service_P3";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 25;
            this.m_Text1.VisibleDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Text1.Width = 23;
=======
            this.m_Text1.Width = 33;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button2
            // 
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.Bold = true;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Button2.DelayMouseInputPeriod = 0;
            this.m_Button2.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button2.FontSizePixels = 15;
=======
            this.m_Button2.FontSizePixels = 12;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Height = 50;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 83;
            this.m_Button2.MultiLine = true;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "Service_P3";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper2;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button2.TextHeight = 36;
            stringintervalmappercf1.DefaultValue = "Raise\r\nPrinthead";
            stringintervalcf1.Value = "Raise\r\nPrinthead";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "Printhead\r\nRaised";
=======
            this.m_Button2.TextHeight = 15;
            stringintervalmappercf1.DefaultValue = "\"Verhoog printkop\"";
            stringintervalcf1.Value = "\"Verhoog printkop\"";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "\"Printkop verhoogd\"";
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            this.m_Button2.TextIntervalMapper = stringintervalmappercf1;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 117;
            this.m_Button2.Top = 59;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -1061038242;
            this.m_Button2.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button2.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button5
            // 
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.Bold = true;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            this.m_Button5.DelayMouseInputPeriod = 0;
            this.m_Button5.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button5.FontSizePixels = 15;
=======
            this.m_Button5.FontSizePixels = 12;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Height = 50;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 83;
            this.m_Button5.MultiLine = true;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "Service_P3";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper3;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button5.TextHeight = 36;
            stringintervalmappercf2.DefaultValue = "Raise\r\nLoad Shelf";
            stringintervalcf3.Value = "Raise\r\nLoad Shelf";
            stringintervalcf4.End = 1D;
            stringintervalcf4.Start = 1D;
            stringintervalcf4.Value = "Load Shelf\r\nRaised";
=======
            this.m_Button5.TextHeight = 15;
            stringintervalmappercf2.DefaultValue = "\"Verhoog laadrek\"";
            stringintervalcf3.Value = "\"Verhoog laadrek\"";
            stringintervalcf4.End = 1D;
            stringintervalcf4.Start = 1D;
            stringintervalcf4.Value = "\"Laadrek verhoogd\"";
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            stringintervalmappercf2.Intervals.Add(stringintervalcf3);
            stringintervalmappercf2.Intervals.Add(stringintervalcf4);
            this.m_Button5.TextIntervalMapper = stringintervalmappercf2;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 117;
            this.m_Button5.Top = 119;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -1061038242;
            this.m_Button5.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button5.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button6
            // 
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.Bold = true;
            this.m_Button6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf3.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval5.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval6.End = 1D;
            brushcfinterval6.Start = 1D;
            brushcfinterval6.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval5);
            brushdynamicsconvertercf3.BrushIntervalMapper.Intervals.Add(brushcfinterval6);
            this.m_Button6.DelayMouseInputPeriod = 0;
            this.m_Button6.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button6.FontSizePixels = 15;
=======
            this.m_Button6.FontSizePixels = 12;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Height = 50;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 217;
            this.m_Button6.MultiLine = true;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "Service_P3";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper4;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button6.TextHeight = 36;
            stringintervalmappercf3.DefaultValue = "Lower\r\nLoad Shelf";
            stringintervalcf5.Value = "Lower\r\nLoad Shelf";
            stringintervalcf6.End = 1D;
            stringintervalcf6.Start = 1D;
            stringintervalcf6.Value = "Load Shelf\r\nLowered";
=======
            this.m_Button6.TextHeight = 15;
            stringintervalmappercf3.DefaultValue = "\"Verlaag laadrek\"";
            stringintervalcf5.Value = "\"Verlaag laadrek\"";
            stringintervalcf6.End = 1D;
            stringintervalcf6.Start = 1D;
            stringintervalcf6.Value = "\"Laadrek verlaagd\"";
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            stringintervalmappercf3.Intervals.Add(stringintervalcf5);
            stringintervalmappercf3.Intervals.Add(stringintervalcf6);
            this.m_Button6.TextIntervalMapper = stringintervalmappercf3;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 117;
            this.m_Button6.Top = 119;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = -1061038242;
            this.m_Button6.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button6.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button7
            // 
            this.m_Button7.BlinkDynamicsValue = false;
            this.m_Button7.Bold = true;
            this.m_Button7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf4.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval7.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval8.End = 1D;
            brushcfinterval8.Start = 1D;
            brushcfinterval8.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval7);
            brushdynamicsconvertercf4.BrushIntervalMapper.Intervals.Add(brushcfinterval8);
            this.m_Button7.DelayMouseInputPeriod = 0;
            this.m_Button7.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button7.FontSizePixels = 15;
=======
            this.m_Button7.FontSizePixels = 12;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button7.ForceTransparency = true;
            this.m_Button7.Height = 50;
            this.m_Button7.IndicatorMargin = null;
            this.m_Button7.Left = 217;
            this.m_Button7.MultiLine = true;
            this.m_Button7.Name = "m_Button7";
            this.m_Button7.RequiresTransparency = true;
            this.m_Button7.ScreenOwnerName = "Service_P3";
            this.m_Button7.SymbolIntervalMapper = symbolintervalmapper5;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button7.TextHeight = 36;
            stringintervalmappercf4.DefaultValue = "Lower\r\nPrinthead";
            stringintervalcf7.Value = "Lower\r\nPrinthead";
            stringintervalcf8.End = 1D;
            stringintervalcf8.Start = 1D;
            stringintervalcf8.Value = "Printhead\r\nLowered";
=======
            this.m_Button7.TextHeight = 15;
            stringintervalmappercf4.DefaultValue = "\"Verlaag printkop\"";
            stringintervalcf7.Value = "\"Verlaag printkop\"";
            stringintervalcf8.End = 1D;
            stringintervalcf8.Start = 1D;
            stringintervalcf8.Value = "\"Printkop verlaagd\"";
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            stringintervalmappercf4.Intervals.Add(stringintervalcf7);
            stringintervalmappercf4.Intervals.Add(stringintervalcf8);
            this.m_Button7.TextIntervalMapper = stringintervalmappercf4;
            this.m_Button7.TextValue = 0D;
            this.m_Button7.TextWidth = 117;
            this.m_Button7.Top = 59;
            this.m_Button7.Value = 0D;
            this.m_Button7.VisibleDynamicsValue = true;
            this.m_Button7.VisualPropertiesHashCode = -1061038242;
            this.m_Button7.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button7.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button
            // 
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.Bold = true;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf5.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval9.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval10.End = 1D;
            brushcfinterval10.Start = 1D;
            brushcfinterval10.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf5.BrushIntervalMapper.Intervals.Add(brushcfinterval9);
            brushdynamicsconvertercf5.BrushIntervalMapper.Intervals.Add(brushcfinterval10);
            this.m_Button.DelayMouseInputPeriod = 0;
            this.m_Button.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button.FontSizePixels = 15;
=======
            this.m_Button.FontSizePixels = 12;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 50;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 217;
            this.m_Button.MultiLine = true;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "Service_P3";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper6;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button.TextHeight = 36;
=======
            this.m_Button.TextHeight = 29;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 117;
            this.m_Button.Top = 179;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1061038242;
            this.m_Button.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Button4
            // 
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.Bold = true;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf6.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval11.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(192)))), ((int)(((byte)(192))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval12.End = 1D;
            brushcfinterval12.Start = 1D;
            brushcfinterval12.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Cyan, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf6.BrushIntervalMapper.Intervals.Add(brushcfinterval11);
            brushdynamicsconvertercf6.BrushIntervalMapper.Intervals.Add(brushcfinterval12);
            this.m_Button4.DelayMouseInputPeriod = 0;
            this.m_Button4.EnabledDynamicsValue = true;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button4.FontSizePixels = 15;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 50;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 83;
=======
            this.m_Button4.FontSizePixels = 12;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 50;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 82;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button4.MultiLine = true;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "Service_P3";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper7;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
            this.m_Button4.TextHeight = 36;
=======
            this.m_Button4.TextHeight = 29;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 117;
            this.m_Button4.Top = 179;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = -1061038242;
            this.m_Button4.Width = 127;
<<<<<<< HEAD:1195 HMI/BuildFiles/Service_P3.cs
=======
            this.m_Button4.WordWrap = true;
>>>>>>> testing/metric:H1195_Beta/BuildFiles/Service_P3.cs
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.DelayMouseInputPeriod = 0;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            this.m_Rectangle.Height = 50;
            this.m_Rectangle.Left = 366;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "Service_P3";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 179;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 97;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.DelayMouseInputPeriod = 0;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 24;
            this.m_Rectangle1.Left = 384;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "Service_P3";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Top = 200;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 57;
            // 
            // m_Text2
            // 
            this.m_Text2.AutoSize = false;
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.Bold = true;
            this.m_Text2.DelayMouseInputPeriod = 0;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 10;
            this.m_Text2.Height = 20;
            this.m_Text2.Left = 366;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2.5D, 0D, 2.5D, 1D);
            this.m_Text2.ScreenOwnerName = "Service_P3";
            this.m_Text2.TextHorizontalAlignment = "Center";
            this.m_Text2.TextVerticalAlignment = "Center";
            this.m_Text2.Top = 179;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 97;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.DelayMouseInputPeriod = 0;
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 14;
            this.m_AnalogNumeric.Height = 24;
            this.m_AnalogNumeric.Left = 384;
            this.m_AnalogNumeric.LimitNumberOfCharacters = true;
            this.m_AnalogNumeric.MaxNumberOfCharacters = 4;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.NumberOfDecimals = 0;
            this.m_AnalogNumeric.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 2D, 2D, 2D);
            this.m_AnalogNumeric.ReadOnly = true;
            this.m_AnalogNumeric.ScreenOwnerName = "Service_P3";
            this.m_AnalogNumeric.Top = 200;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 57;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(480, 272);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Service_P3";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Service_P3 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
            this.SecurityGroups = SecurityGroups.Group_01 | SecurityGroups.Group_03;
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Service_P3) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Button7);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "Service_P2", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Service_P2.Show();
        }
        
        private void m_Button2_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_retractCommand.SetTag();
        }
        
        private void m_Button2_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_retractCommand.ResetTag();
        }
        
        private void m_Button2_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_retractCommand.ResetTag();
        }
        
        private void m_Button5_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_extendCommand.SetTag();
        }
        
        private void m_Button5_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_extendCommand.ResetTag();
        }
        
        private void m_Button5_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_extendCommand.ResetTag();
        }
        
        private void m_Button6_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_retractCommand.SetTag();
        }
        
        private void m_Button6_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_retractCommand.ResetTag();
        }
        
        private void m_Button6_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_loadPlateService_retractCommand.ResetTag();
        }
        
        private void m_Button7_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_extendCommand.SetTag();
        }
        
        private void m_Button7_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_extendCommand.ResetTag();
        }
        
        private void m_Button7_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_printHeadService_extendCommand.ResetTag();
        }
        
        private void m_Button_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_stopJawCycleTest.SetTag();
        }
        
        private void m_Button_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_stopJawCycleTest.ResetTag();
        }
        
        private void m_Button_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_stopJawCycleTest.ResetTag();
        }
        
        private void m_Button4_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_startJawCycleTest.SetTag();
        }
        
        private void m_Button4_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_startJawCycleTest.ResetTag();
        }
        
        private void m_Button4_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Application_HMIData_startJawCycleTest.ResetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Service_P3));
            this.m_Text.Text = resources.GetText("Service_P3.Text.Text", "Service Page");
            this.m_Text1.Text = resources.GetText("Service_P3.Text1.Text", "3/3");
            this.m_Button2.Text = resources.GetText("Service_P3.Button2.Text", "Raise\r\nPrinthead");
            this.m_Button5.Text = resources.GetText("Service_P3.Button5.Text", "Raise\r\nLoad Shelf");
            this.m_Button6.Text = resources.GetText("Service_P3.Button6.Text", "Lower\r\nLoad Shelf");
            this.m_Button7.Text = resources.GetText("Service_P3.Button7.Text", "Lower\r\nPrinthead");
            this.m_Button.Text = resources.GetText("Service_P3.Button.Text", "Jaw Cycle\r\nTest Cancel");
            this.m_Button4.Text = resources.GetText("Service_P3.Button4.Text", "Jaw Cycle\r\nTest Start");
            this.m_Text2.Text = resources.GetText("Service_P3.Text2.Text", "Jaw Cycles");
            resources.ApplyTexts(this.m_Button2, "Texts", "Service_P3.Button2.Texts[0]", "Raise\r\nPrinthead", "Service_P3.Button2.Texts[1]", "Printhead\r\nRaised");
            resources.ApplyTexts(this.m_Button5, "Texts", "Service_P3.Button5.Texts[0]", "Raise\r\nLoad Shelf", "Service_P3.Button5.Texts[1]", "Load Shelf\r\nRaised");
            resources.ApplyTexts(this.m_Button6, "Texts", "Service_P3.Button6.Texts[0]", "Lower\r\nLoad Shelf", "Service_P3.Button6.Texts[1]", "Load Shelf\r\nLowered");
            resources.ApplyTexts(this.m_Button7, "Texts", "Service_P3.Button7.Texts[0]", "Lower\r\nPrinthead", "Service_P3.Button7.Texts[1]", "Printhead\r\nLowered");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled());
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Service_P3) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_retractCommand"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button2.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_startJawCycleTest"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button4.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_stopJawCycleTest"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf5);
            this.m_Button.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_stopJawCycleTest"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printerInUse"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button7.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_extendedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf4);
            this.m_Button7.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_extendedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button7.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_extendCommand"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button7.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateInUse"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button6.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.alwaysOff"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button6.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_startJawCycleTest"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf6);
            this.m_Button4.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_retractedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf3);
            this.m_Button6.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_retractCommand"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button6.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateInUse"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button5.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding15 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("VisibleDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.alwaysOff"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button5.DataBindings.Add(dynamicBinding15);
            this.m_DynamicBindings.Add(dynamicBinding15);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding16 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_extendedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Button5.DataBindings.Add(dynamicBinding16);
            this.m_DynamicBindings.Add(dynamicBinding16);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding17 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_extendedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button5.DataBindings.Add(dynamicBinding17);
            this.m_DynamicBindings.Add(dynamicBinding17);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding18 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_extendCommand"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button5.DataBindings.Add(dynamicBinding18);
            this.m_DynamicBindings.Add(dynamicBinding18);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding19 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("EnabledDynamicsValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printerInUse"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.BoolDynamicsConverterCF.TrueValueOne);
            this.m_Button2.DataBindings.Add(dynamicBinding19);
            this.m_DynamicBindings.Add(dynamicBinding19);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding20 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_retractedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Button2.DataBindings.Add(dynamicBinding20);
            this.m_DynamicBindings.Add(dynamicBinding20);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding21 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_printHeadService_retractedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button2.DataBindings.Add(dynamicBinding21);
            this.m_DynamicBindings.Add(dynamicBinding21);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding22 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_loadPlateService_retractedFeedback"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button6.DataBindings.Add(dynamicBinding22);
            this.m_DynamicBindings.Add(dynamicBinding22);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding23 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Application_HMIData_jawCycleTestCycles"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding23);
            this.m_DynamicBindings.Add(dynamicBinding23);
        }
    }
}
#pragma warning restore 0114
#pragma warning restore 0108
